class EventTypes:
    RUN_STARTED = "run.started"
    CONTEXT_ASSEMBLED = "context.assembled"
    PLAN_CREATED = "plan.created"
    ACTION_SELECTED = "action.selected"
    TOOL_STARTED = "tool.started"
    TOOL_COMPLETED = "tool.completed"
    TOOL_FAILED = "tool.failed"
    VERIFICATION_COMPLETED = "verification.completed"
    CHECKPOINT_SAVED = "checkpoint.saved"
    STATE_TRANSITIONED = "state.transitioned"
    RUN_COMPLETED = "run.completed"
    RUN_BLOCKED = "run.blocked"
    RUN_FAILED = "run.failed"
